### ISSUE TITLE
Where's documentation on how to use?

### ISSUE THREAD

**Issue by bananabrann** [lualdap/lualdap#13]
This includes things like what to call, how to call them, etc.

I'm not familiar enough with C and working within this code, and following the code editor suggestions doesn't yield details of param expectations and such. Would be nice to have docs, even if they're short and simple, about methods and return types.

**Comment by linuxmaniac** [comment]
There's a doc directory in the repository.

https://htmlpreview.github.io/?https://raw.githubusercontent.com/lualdap/lualdap/master/doc/us/index.html

**Comment by bananabrann** [comment]
D'oh. Thank you!
